# General environment settings
domain_name: 'cheetah'
task_name: 'run'
seed: 1
work_dir: '.'

# Image and frame settings
image_size: 84
action_repeat: 1
frame_stack: 3
total_frames: 1000
img_source: null

# Resource file settings
resource_files: null
eval_resource_files: null

# Replay buffer settings
replay_buffer_capacity: 10000

# Training settings
agent: 'bisim'
init_steps: 1000
num_train_steps: 1000000
batch_size: 512
k: 3
bisim_coef: 0.5
load_encoder: null

# Evaluation settings
eval_freq: 10
num_eval_episodes: 20

# Learning rates and update frequencies
critic_lr: 0.001
critic_beta: 0.9
critic_tau: 0.005
critic_target_update_freq: 2
actor_lr: 0.001
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2
encoder_lr: 0.001
encoder_tau: 0.005
decoder_lr: 0.001
decoder_update_freq: 1
alpha_lr: 0.001
alpha_beta: 0.9

# Encoder/decoder settings
encoder_type: 'pixel'
encoder_feature_dim: 50
encoder_stride: 1
decoder_type: 'pixel'
decoder_weight_lambda: 0.0
num_layers: 4
num_filters: 32

# Soft Actor-Critic settings
discount: 0.99
init_temperature: 0.01

# Miscellaneous settings
save_tb: true
save_model: true
save_buffer: true
save_video: true
transition_model_type: ''
render: false
port: 2000
